
== SOIL bindings

All the functions listed here are members of the *soil* table.

* _string_ = *last_result*( )

* _n_ = *channels*(<<channels,_channels_>>) +
[small]#Returns the number of channels corresponding to the given _channels_ string.#

* <<data, _data_>>, _width_, _height_, <<channels,_channels_>> = 
*load_image*(_filename_, <<forcechannels,_forcechannels_>>)

* <<data, _data_>>, _width_, _height_, <<channels,_channels_>> = 
*load_image_from_memory*(<<buffer,_buffer_>>, <<forcechannels,_forcechannels_>>)

* _boolean_, _errmsg_ = *save_image*(_filename_, <<imagetype,_imagetype_>>, _width_, _height_, <<channels,_channels_>>, <<flags,_flags_>>)

* _boolean_, _errmsg_ = *save_screenshot*(_filename_, <<imagetype,_imagetype_>>, _x_, _y_, _width_, _height_)


NOTE: The following functions require OpenGL. In order to use them,
you can create a GL context using a windowing library such as 
https://github.com/stetre/moonglfw[MoonGLFW], and initialize it with
https://github.com/stetre/moongl[MoonGL] (see the examples for more details).

* _texid_ = *load_texture*(_filename_, <<forcechannels,_forcechannels_>>, <<texid, _texid_>>, <<flags,_flags_>>)

* _texid_ = *load_cubemap*(_xposfilename_, _xnegfilename_, _yposfilename_, _ynegfilename_, _zposfilename_, _znegfilename_, <<forcechannels,_forcechannels_>>, <<texid, _texid_>>, <<flags,_flags_>>)

* _texid_ = *load_single_cubemap*(_filename_, <<faceorder,_faceorder_>>, <<forcechannels,_forcechannels_>>, <<texid, _texid_>>, <<flags,_flags_>>)

* _texid_ = *load_hdr_texture*(_filename_, <<fakehdr, _fakehdr_>>, <<rescaletomax, _rescaletomax_>>, <<texid, _texid_>>, <<flags,_flags_>>)

* _texid_ = *load_texture_from_memory*(<<buffer,_buffer_>>, <<forcechannels,_forcechannels_>>, <<texid, _texid_>>, <<flags,_flags_>>)

* _texid_ = *load_cubemap_from_memory*(<<buffer,_xposbuffer_>>, <<buffer,_xnegbuffer_>>, <<buffer,_yposbuffer_>>, <<buffer,_ynegbuffer_>>, <<buffer,_zposbuffer_>>, <<buffer,_znegbuffer_>>, <<forcechannels,_forcechannels_>>, <<texid, _texid_>>, <<flags,_flags_>>)

* _texid_ = *load_single_cubemap_from_memory*(<<buffer,_buffer_>>, <<faceorder,_faceorder_>>, <<forcechannels,_forcechannels_>>, <<texid, _texid_>>, <<flags,_flags_>>)

* _texid_ = *create_texture*(<<data, _data_>>, _width_, _height_, <<channels,_channels_>>, <<texid, _texid_>>, <<flags,_flags_>>)

* _texid_ = *create_single_cubemap*(<<data, _data_>>, _width_, _height_, <<channels,_channels_>>, <<faceorder,_faceorder_>>, <<texid, _texid_>>, <<flags,_flags_>>)


'''

[[buffer]]
[small]#*buffer*, *xposbuffer*, *xnegbuffer*, ...: binary string.#

[[channels]]
[small]#*channels*: '_luminous_' (greyscale), '_luminous/alpha_', '_rgb_', '_rgba_'.#

[[data]]
[small]#*data*: binary string.#

[[faceorder]]
[small]#*faceorder*: a permutation of the string 'ESWNUD' (East, South, West, North, Up, Down).#

[[fakehdr]]
[small]#*fakehdr*: '_rgbe_', '_rgbdiva_', '_rgbdiva2_'.#

[[flags]]
[small]#*flags*: a bitfield. May be passed either as an integer code obtained by combining
soil.FLAG_XXX values (corresponding to SOIL_FLAG_XXX defines) or as a sequence of literals 
from the set listed below. +
Values: '_power of two_', '_mipmaps_', '_texture repeats_', '_multiply alpha_', '_invert y_', '_compress to dxt_', '_dds load direct_', '_ntsc safe rgb_', '_ycocg_', '_texture rectangle_'.#

[[forcechannels]]
[small]#*forcechannels*: '_auto_', or one of <<channels, _channels_>>.#

[[imagetype]]
[small]#*imagetype*: '_tga_', '_bmp_', '_dds_'.#

[[rescaletomax]]
[small]#*rescaletomax*: boolean.#

[[texid]]
[small]#*texid* id of OpenGL texture to reuse (=0 or _nil_ to create a new texture).#


