
== KTX functions


This section describes MoonSOIL additions to handle textures in the 
https://www.khronos.org/opengles/sdk/tools/KTX/[KTX File Format]. 

_(Note that these are MoonSOIL additions, i.e. not bindings to SOIL.)_

* <<ktxtexture, _ktxtexture_>> = *load_ktx*(_filename_) +
[small]#Loads a texture from a KTX file and returns its contents in a table. +
This function raises a Lua error if an error occurs while parsing the file.#

* _data_ = *ktx_data*(<<ktxtexture, _ktxtexture_>>) +
[small]#Returns a binary string obtained by concatenating the _data_ fields of all
the _levels_ in the given _ktxtexture_ (i.e., the whole texture data, padding included).#

* _string_ = *ktx_tostring*(<<ktxtexture, _ktxtexture_>>) +
[small]#Returns a printable string with the contents of the given _ktxtexture_.#

'''

[[ktxtexture]]
[small]#*ktxtexture* = { +
_filename_: string, +
_little_endian_: boolean, +
_texture_type_: <<texturetype, texturetype>>, +
_gl_type_: <<gltype, gltype>>, +
_gl_format_: <<glformat, glformat>>, +
_gl_internal_format_: <<glinternalformat, glinternalformat>>, +
_gl_base_internal_format_: <<glformat, glformat>>, +
_array_elements_: integer, +
_faces_: integer, +
_mipmap_levels_: integer, +
_key_value_data_: binary string, +
_levels_: {<<mipmaplevel, mipmaplevel>>}, +
} (rfr: https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/[KTF File Format Specification])#

[[mipmaplevel]]
[small]#*mipmaplevel* = { +
_width_: integer, +
_height_: integer, +
_depth_: integer, +
_size_: integer (image size or face size, see note below), +
_padding_: integer (mip padding or cube padding, see note below), +
_data_: binary string (see note below), +
} +
Note: the meaning of the _size_ and _padding_ fields and the composition of the _data_ field
depend on the _texture_type_ this _mipmap_level_ belongs to. In particular: +
pass:[-] if _texture_type_ is '_cube map_', then _size_ and _padding_ refer to a single face, and _data_ contains _6*(size + padding)_ bytes concatenating the data for the 6 faces, in order from the first to the sixth; +
pass:[-] for all other texture types, _data_ contains _size + padding_ bytes, and is composed of the image of this level followed by the mip padding; +
pass:[-] for array textures (including '_cube map array_'), the level image is the concatenation of the images for all the array elements, each composed of _size/array_elements_ bytes.#

[[texturetype]]
[small]#*texturetype*: string literal +
Values: '_1d_', '_1d array_', '_2d_', '_2d array_', '_3d_', '_cube map_', '_cube map array_'.#


[[gltype]]
[small]#*gltype*: string literal +
Values:@@TODO.#

[[glformat]]
[small]#*glformat*: string literal +
Values:@@TODO.#

[[glinternalformat]]
[small]#*glinternalformat*: string literal +
Values:@@TODO.#

