
== Preface

This is the reference manual of *MoonSOIL*, which is a 
http://www.lua.org[*Lua*] binding library for the
http://www.lonesock.net/soil.html[Simple OpenGL Image Library (SOIL)].
footnote:[
This manual is written in
http://www.methods.co.nz/asciidoc/[AsciiDoc], rendered with
http://asciidoctor.org/[AsciiDoctor] and a CSS from the
https://github.com/asciidoctor/asciidoctor-stylesheet-factory[AsciiDoctor Stylesheet Factory].
The PDF version is produced with
https://github.com/asciidoctor/asciidoctor-pdf[AsciiDoctor-Pdf].]

It is assumed that the reader is familiar with both SOIL and the Lua programming language.

For convenience of reference, this document contains external (deep) links to the 
http://www.lua.org/manual/5.3/manual.html[Lua Reference Manual].

=== Getting and installing

For installation intructions, refer to the README file in the 
https://github.com/stetre/moonsoil[*MoonSOIL official repository*]
on GitHub.

////
The *official repository* of MoonSOIL is on GitHub at the following link:
*https://github.com/stetre/moonsoil* .

MoonSOIL runs on GNU/Linux and requires 
*http://www.lua.org[Lua]* version 5.3 or greater, and 
*http://www.lonesock.net/soil.html[SOIL]*.

To install MoonSOIL, download the 
https://github.com/stetre/moonsoil/releases[latest release] and do the following:

[source,shell]
----
# ... download moonsoil-0.1.tar.gz ...
[ ]$ tar -zxpvf moonsoil-0.1.tar.gz
[ ]$ cd moonsoil-0.1
[moonsoil-0.1]$ make
[moonsoil-0.1]$ make check
[moonsoil-0.1]$ sudo make install
----

The _$make check_ command shows you what will be installed and where (please read
its output before executing _$make install_).
By default, MoonSOIL installs its components in subdirectories of `/usr/local/`
(and creates such directories, if needed).
This behaviour can be changed by defining PREFIX with the desired alternative 
base installation directory. For example, this will install the components
in `/home/joe/local`:

[source,shell]
----
[moonsoil-0.1]$ make
[moonsoil-0.1]$ make install PREFIX=/home/joe/local
----
////

=== Module organization

The MoonSOIL module is loaded using Lua's 
http://www.lua.org/manual/5.3/manual.html#pdf-require[require]() and
returns a table containing the functions it provides 
(as usual with Lua modules). This manual assumes that such
table is named *soil*, i.e. that it is loaded with:

[source,lua,indent=1]
----
soil = require("moonsoil")
----

but nothing forbids the use of a different name.

=== Examples

A few examples can be found in the *examples/* directory of the release package.

=== License

MoonSOIL is released under the *MIT/X11 license* (same as
http://www.lua.org/license.html[Lua], and with the same only requirement to give proper
credits to the original author). 
The copyright notice is in the LICENSE file in the base directory
of the https://github.com/stetre/moonsoil[official repository] on GitHub.

<<<
